apiVersion: apps/v1
kind: Deployment
metadata:
  name: bean-disease-api
  labels:
    app: bean-disease-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: bean-disease-api

  template:
    metadata:
      labels:
        app: bean-disease-api

    spec:
      automountServiceAccountToken: false

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: bean-disease-api
          image: zharasbek/bean-disease-api:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"

          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3